version: '3.8'

services:
  ethereum:
    image: ethereum/client-go:stable
    container_name: social-ethereum
    restart: unless-stopped
    command: >
      --light
      --http
      --http.addr 0.0.0.0
      --http.port 8545
      --http.corsdomain "*"
      --http.api eth,net,web3,personal,debug
      --ws
      --ws.addr 0.0.0.0
      --ws.port 8546
      --ws.api eth,net,web3
      --ws.origins "*"
      --syncmode light
      --maxpeers 50
      --cache 1024
      --datadir /ethereum-data
      --verbosity 3
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - ethereum_data:/ethereum-data
    networks:
      - ethereum-network

volumes:
  ethereum_data:
    driver: local

networks:
  ethereum-network:
    driver: bridge
