version: "3.9"
services:
  mongo:
    image: mongo:7
    container_name: mongo
    restart: unless-stopped
    ports:
      - "127.0.0.1:27017:27017" # 仅本机访问，更安全；需要外部访问再改成 0.0.0.0
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: rootpass123
    volumes:
      - ./mongo-data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--quiet", "--eval", "db.runCommand({ ping: 1 })"]
      interval: 10s
      timeout: 5s
      retries: 5

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: unless-stopped
    ports:
      - "127.0.0.1:8081:8081"  # MongoDB网页界面
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: rootpass123
      ME_CONFIG_MONGODB_URL: mongodb://root:rootpass123@mongo:27017/
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123
    depends_on:
      - mongo
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8081"]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    container_name: redis
    restart: unless-stopped
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "redispass123"]
    ports:
      - "127.0.0.1:6379:6379"
    volumes:
      - ./redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "-a", "redispass123", "PING"]
      interval: 10s
      timeout: 5s
      retries: 5

  neo4j:
    image: neo4j:5-community
    container_name: neo4j
    restart: unless-stopped
    ports:
      - "127.0.0.1:7474:7474" # Neo4j Browser (HTTP)
      - "127.0.0.1:7687:7687" # Bolt
    environment:
      NEO4J_AUTH: neo4j/neo4jpass123
      NEO4J_server_default__listen__address: "0.0.0.0"
      NEO4J_server_http_listen__address: ":7474"
      NEO4J_server_bolt_listen__address: ":7687"
      NEO4J_server_directories_plugins: "/plugins"
    volumes:
      - ./neo4j-data:/data
      - ./neo4j-logs:/logs
      - ./neo4j-plugins:/plugins
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://localhost:7474/browser || exit 1"]
      interval: 15s
      timeout: 10s
      retries: 10
